[package]
name = "async-transport"
version = "0.0.0"
authors = ["Rusty Rain <y@liu.mx>"]
edition = "2021"
description = "asynchronous transports, i.e., UDP, TCP, etc."
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-transport"
repository = "https://github.com/retty-io/async-transport"
homepage = "https://retty.io"
keywords = ["networking", "protocols"]
categories = [ "network-programming", "asynchronous" ]

[dependencies]
