codecov:
  require_ci_to_pass: yes
  max_report_age: off
  token: 7f2e609d-4e73-4f2e-9bf1-1d93c8e6567d

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
       enabled: no
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
